Assignment/Assignment/Controllers/Assignment3Controller.cs
using BusinessLayer;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Assignment.Controllers
{
    public class Assignment3Controller : Controller
    {
        #region "View Employees using Business Layer"
        /// <summary>
        /// View to display user details using ADO .NET
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            List<Employee> employees = employeeBusinessLayer.Employees.ToList();
            return View(employees);
        }
        #endregion
    }
}

Assignment/Assignment/Controllers/Assignment5Controller.cs
using Assignment.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Assignment.Controllers
{
    public class Assignment5Controller : Controller
    {
        #region "Context Declaration"
        // The database
        private UserDetailsContext db = new UserDetailsContext();
        #endregion

        #region "Index View"
        // GET: Assignmnet5        
        /// <summary>
        /// Get user details using Entity Framework
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Department);
            return View(users.ToList());
        }
        #endregion

        #region "Details View"
        // GET: Assignmnet5/Details/5        
        /// <summary>
        /// View Details of particular user using Entity Framework
        /// </summary>
        /// <param name="id">The user ID.</param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        #endregion

        #region "Create View"
        // GET: Assignmnet5/Create        
        /// <summary>
        /// Display form to create user
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "DeptName");
            return View();
        }

        // POST: Assignmnet5/Create        
        /// <summary>
        /// Get user details from the user and insert in database
        /// </summary>
        /// <param name="user">The user.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,Name,DeptId,City,Gender")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "DeptName", user.DeptId);
            return View(user);
        }
        #endregion

        #region "Edit View"
        // GET: Assignmnet5/Edit/5        
        /// <summary>
        /// Display edit form with previous details
        /// </summary>
        /// <param name="id">The user ID.</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "DeptName", user.DeptId);
            return View(user);
        }

        // POST: Assignmnet5/Edit/5        
        /// <summary>
        /// Get user changes and update in database
        /// </summary>
        /// <param name="user">The user.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Name,DeptId,City,Gender")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "DeptName", user.DeptId);
            return View(user);
        }
        #endregion

        #region "Delete View"
        // GET: Assignmnet5/Delete/5        
        /// <summary>
        /// Display user details before deleting
        /// </summary>
        /// <param name="id">The user ID.</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Assignmnet5/Delete/5        
        /// <summary>
        /// Deletes the user from database if user confirms delete
        /// </summary>
        /// <param name="id">The user ID.</param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region "Dispose Method"        
        /// <summary>
        /// Releases unmanaged resources and optionally releases managed resources.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion

    }
}

Assignment/Assignment/Views/Assignment5/Create.cshtml
@model Assignment.Models.User

@{
    ViewBag.Title = "Assignment5-Add User";
}

<div class="container py-5 my-5">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>User</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DeptId, "Department Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DeptId", null, "Select Department", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DeptId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Gender", new List<SelectListItem>
                     {
                     new SelectListItem { Text = "Male", Value="Male" },
                     new SelectListItem { Text = "Female", Value="Female" }
                     }, "Select Gender", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success mr-2" />
                    @Html.ActionLink("Back to List", "Index", "Assignment5", new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }
</div>

Assignment/Assignment/Views/Assignment5/Delete.cshtml
@model Assignment.Models.User

@{
    ViewBag.Title = "Assignment5-Edit User";
}

<div class="container py-5 my-3">
    <h3 class="text-danger">Are you sure you want to delete this?</h3>
    <h4 class="text-danger">Delete User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DeptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DeptName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "Index", "Assignment5", new { @class = "btn btn-info ml-3" })
        </div>
    }
</div>

Assignment/Assignment/Views/Assignment5/Details.cshtml
@model Assignment.Models.User

@{
    ViewBag.Title = "Assignment5-User Details";
}

<div class="container py-5 my-3">
    <h4 class="text-info">User Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DeptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DeptName)
        </dd>

    </dl>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }, new { @class = "btn btn-primary mr-3" })
        @Html.ActionLink("Back to List", "Index", "Assignment5", new { @class = "btn btn-info" })
    </p>
</div>

Assignment/Assignment/Views/Assignment5/Edit.cshtml
@model Assignment.Models.User

@{
    ViewBag.Title = "Assignment5-Edit User";
}

<div class="container py-5 my-3">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 class="text-primary">Edit User</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UserId)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DeptId, "Department Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DeptId", null, "Select Department", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DeptId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Gender", new List<SelectListItem>
                     {
                     new SelectListItem { Text = "Male", Value="Male" },
                     new SelectListItem { Text = "Female", Value="Female" }
                     }, "Select Gender", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success mr-2" />
                    @Html.ActionLink("Back to List", "Index", "Assignment5", new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }
</div>

Assignment/Assignment/Views/Assignment5/Index.cshtml
@model IEnumerable<Assignment.Models.User>

@{
    ViewBag.Title = "Assignment5-Index";
}


<div class="container mx-auto w-100 py-5 my-5">
    <h2 class="text-center mb-3">Employees</h2>
    <div class="row py-2 px-3 float-right">
        @Html.ActionLink(" Add New", "Create", "Assignment3", new { @class = "fa fa-plus fa-lg text-info" })
    </div>
    <br />
    <div class="rTable text-center w-100 mx-auto">
        <div class="rTableRow bg-dark text-white">
            <div class="rTableHead"><strong>@Html.DisplayNameFor(model => model.Name)</strong></div>
            <div class="rTableHead"><strong>@Html.DisplayNameFor(model => model.City)</strong></div>
            <div class="rTableHead"><strong>@Html.DisplayNameFor(model => model.Gender)</strong></div>
            <div class="rTableHead"><strong>@Html.DisplayNameFor(model => model.Department.DeptName)</strong></div>
            <div class="rTableHead"><strong>Edit</strong></div>
            <div class="rTableHead"><strong>Details</strong></div>
            <div class="rTableHead"><strong>Delete</strong></div>
        </div>
        @foreach (var item in Model)
        {
            <div class="rTableRow">
                <div class="rTableCell">@Html.DisplayFor(modelItem => item.Name)</div>
                <div class="rTableCell">@Html.DisplayFor(modelItem => item.City)</div>
                <div class="rTableCell">@Html.DisplayFor(modelItem => item.Gender)</div>
                <div class="rTableCell">@Html.DisplayFor(modelItem => item.Department.DeptName)</div>
                <div class="rTableCell">@Html.ActionLink(" ", "Edit", new { id = item.UserId }, new { @class = "fa fa-edit text-primary" })</div>
                <div class="rTableCell">@Html.ActionLink(" ", "Details", new { id = item.UserId }, new { @class = "fa fa-info-circle text-info" })</div>
                <div class="rTableCell">@Html.ActionLink(" ", "Delete", new { id = item.UserId }, new { @class = "fa fa-trash text-danger" })</div>
            </div>
        }
    </div>
</div>