Assignment/Assignment/Controllers/Assignment1Controller.cs
using System;
using System.Web.Mvc;
using Assignment.Models;

namespace Assignment.Controllers
{
    public class Assignment1Controller : Controller
    {
        #region "Display in Index view of Assignment1 controller"
        /// <summary>
        /// Display Greetings according to the time to the view
        /// </summary>
        /// <returns></returns>
        public ViewResult Index()
        {
            ViewBag.Greeting = (DateTime.Now.Hour < 12) ? "Good Morning" : (((DateTime.Now.Hour >= 12) && (DateTime.Now.Hour <= 17)) ? "Good Afternoon" : (((DateTime.Now.Hour >= 17) && (DateTime.Now.Hour <= 20)) ? "Good Evening" : "Good Night"));
            return View();
        }
        #endregion

        #region "RSVP Form to get Guest data"
        /// <summary>
        /// Show Invitation form
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ViewResult RSVPForm()
        {
            return View();
        }
        #endregion

        #region "Check whether form is valid and redirect to thanks view"
        /// <summary>
        /// Check whether RSVP Form is valid and redirect to Thanks view
        /// </summary>
        /// <param name="guestResponse"></param>
        /// <returns></returns>
        [HttpPost]
        public ViewResult RSVPForm(GuestResponse guestResponse)
        {
            if (ModelState.IsValid)
            {
                return View("Thanks", guestResponse);
            }
            else
            {
                return View();
            }
        }
        #endregion
    }
}

Assignment/Assignment/Controllers/Assignment2Controller.cs
using Assignment.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Assignment.Controllers
{
    public class Assignment2Controller : Controller
    {
        #region "Get list of user from Database and display in view"
        /// <summary>
        /// Get list of user from database and send to view
        /// </summary>
        /// <returns></returns>
        public ActionResult Details(int? deptId)
        {
            if (deptId == null)
            {
                return RedirectToAction("Index");
            }
            UserContext userContext = new UserContext();
            List<Users> user = userContext.Users.Where(u => u.DeptId == deptId).ToList();
            return View(user);
        }
        #endregion

        #region "Get list of department from Database and display in view"
        /// <summary>
        /// Get details of department from database and send to view
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            UserContext userContext = new UserContext();
            List<Departments> department = userContext.Departments.ToList();
            return View(department);
        }
        #endregion
    }
}

Assignment/Assignment/Controllers/Assignment3Controller.cs
using BusinessLayer;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Assignment.Controllers
{
    public class Assignment3Controller : Controller
    {
        #region "View Employees using Business Layer"
        /// <summary>
        /// View to display user details using ADO .NET
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            List<Employee> employees = employeeBusinessLayer.Employees.ToList();
            return View(employees);
        }
        #endregion
    }
}

Assignment/Assignment/Controllers/Assignment4Controller.cs
using BusinessLayer;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Assignment.Controllers
{
    public class Assignment4Controller : Controller
    {
        #region "Index View to display list of employees using ADO .NET"
        /// <summary>
        /// View to display user details using ADO .NET
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            List<Employee> employees = employeeBusinessLayer.Employees.ToList();
            return View(employees);
        }
        #endregion

        #region "Create View to Add a new Employee using ADO .NET"
        /// <summary>Creates this instance.</summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>Creates the specified employee.</summary>
        /// <param name="employee">The employee.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
                employeeBusinessLayer.AddEmployee(employee);
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region "Edit View to Update Employee using ADO .NET"
        /// <summary>Edits the specified identifier.</summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            Employee employee = employeeBusinessLayer.Employees.Single(emp => emp.ID == id);
            return View(employee);
        }

        /// <summary>Edits the specified employee.</summary>
        /// <param name="employee">The employee.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
                employeeBusinessLayer.UpdateEmployee(employee);
                return RedirectToAction("Index");
            }
            return View(employee);
        }
        #endregion

        #region "Delete Action to Delete Employee using ADO .NET"
        /// <summary>Deletes the specified identifier.</summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            employeeBusinessLayer.DeleteEmployee(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

Assignment/Assignment/Views/Shared/_CommentForm.cshtml
@model IEnumerable<Assignment.Models.userResponse>

<div class="rTable text-center w-100 mx-auto">
    <div class="rTableRow bg-dark text-white">
        <div class="rTableHead"><strong>@Html.DisplayNameFor(model => model.Name)</strong></div>
        <div class="rTableHead"><strong>@Html.DisplayNameFor(model => model.Comments)</strong></div>
    </div>
    @foreach (var item in Model)
    {
        <div class="rTableRow">
            <div class="rTableCell">@Html.DisplayFor(modelItem => item.Name)</div>
            <div class="rTableCell">@Html.Raw(item.Comments)</div>
        </div>
    }
</div>

Assignment/Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-expand-md bg-light navbar-light w-100">
        @Html.ActionLink("MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Assignments
                    </a>
                    <div class="dropdown-menu">
                        @Html.ActionLink("Assignment 1", "Index", "Assignment1", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Assignment 2", "Index", "Assignment2", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Assignment 3", "Index", "Assignment3", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Assignment 4", "Index", "Assignment4", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Assignment 5", "Index", "Assignment5", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Assignment 6", "Index", "Assignment6", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Assignment 7", "Index", "Assignment7", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Assignment 9 & 10", "Index", "Assignment9", new { area = "" }, new { @class = "dropdown-item" })                       
                        @Html.ActionLink("Assignment 11", "Index", "Assignment11", new { area = "" }, new { @class = "dropdown-item" })
                    </div>
                </li>
            </ul>
        </div>
    </div>

    @RenderBody()

    <div class="footer bg-light text-center py-3 w-100 position-fixed">
        <div class="container">
            <span class="text-muted">&copy; @DateTime.Now.Year - Assignment</span>
        </div>
    </div>

</body>
</html>