Assignment/Assignment/Controllers/Assignment7Controller.cs
using Assignment.Models;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Assignment.Controllers
{
    public class Assignment7Controller : Controller
    {
        #region "Database Context"
        /// <summary>The database</summary>
        private UserDetailsContext db = new UserDetailsContext();
        #endregion

        #region "List of Users and their comments"
        /// <summary>Indexes this instance.</summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(db.userResponses.ToList());
        }
        #endregion

        #region "Add a new comment"
        /// <summary>Creates this instance.</summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id,Name,Comments")] userResponse userResponse)
        {
            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.Append(HttpUtility.HtmlEncode(userResponse.Comments));
            stringBuilder.Replace("&lt;b&gt;", "<b>");
            stringBuilder.Replace("&lt;/b&gt;", "</b>");
            stringBuilder.Replace("&lt;u&gt;", "<u>");
            stringBuilder.Replace("&lt;/u&gt;", "</u>");
            stringBuilder.Replace("&lt;i&gt;", "<i>");
            stringBuilder.Replace("&lt;/i&gt;", "</i>");
            userResponse.Comments = stringBuilder.ToString();

            string strEncodedName = HttpUtility.HtmlEncode(userResponse.Name);
            userResponse.Name = strEncodedName;
            if (ModelState.IsValid)
            {
                db.userResponses.Add(userResponse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userResponse);
        }
        #endregion

        #region "Dispose"
        /// <summary>Releases unmanaged resources and optionally releases managed resources.</summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

Assignment/Assignment/Views/Assignment7/Create.cshtml
@model Assignment.Models.userResponse

@{
    ViewBag.Title = "Assignment7-Add User Response";
}

<div class="container py-5 my-5">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>User Response</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Comments, htmlAttributes: new { @class = "form-control", @rows = "4" })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success mr-2" />
                    @Html.ActionLink("Back to List", "Index", "Assignment7", new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }
</div>

Assignment/Assignment/Views/Assignment7/Index.cshtml
@{
    ViewBag.Title = "Assignment7-View Users Responses";
}

<div class="container mx-auto w-100 py-5 my-5">
    <h2 class="text-center mb-3">Employees</h2>
    <div class="row py-2 px-3 float-right">
        @Html.ActionLink(" Add New", "Create", "Assignment7", new { @class = "fa fa-plus fa-lg text-info" })
    </div>
    <br />
    @Html.Partial("_CommentForm")
</div>