Assignment/Assignment/Controllers/Assignment9Controller.cs
using Assignment.Models;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using System;
using System.Collections.Generic;

namespace Assignment.Controllers
{
    public class Assignment9Controller : Controller
    {
        #region Database
        /// <summary>The database</summary>
        private UserDetailsContext db = new UserDetailsContext();
        #endregion

        #region View Departments
        /// <summary>Indexes the specified search.</summary>
        /// <param name="search">The search.</param>
        /// <param name="page">The page.</param>
        /// <param name="sortBy">The sort by.</param>
        /// <returns></returns>
        public ActionResult Index(string search, int? page, string sortBy)
        {
            ViewBag.DeptNameSort = String.IsNullOrEmpty(sortBy) ? "DeptName desc" : "";
            ViewBag.DeptLocationSort = String.IsNullOrEmpty(sortBy) ? "DeptLocation desc" : "";

            var department = db.Departments.AsQueryable();

            switch (sortBy)
            {
                case "DeptName desc":
                    department = department.OrderByDescending(x => x.DeptName);
                    break;
                case "DeptLocation desc":
                    department = department.OrderByDescending(x => x.DeptLocation);
                    break;
                default:
                    department = department.OrderBy(x => x.DeptName);
                    break;
            }

            return View(department.Where(d => d.DeptName.StartsWith(search) || d.DeptLocation.StartsWith(search) || search == null).ToList().ToPagedList(page ?? 1, 3));
        }
        #endregion

        #region Delete Multiple Departments
        /// <summary>Deletes the specified department ids to delete.</summary>
        /// <param name="departmentIdsToDelete">The department ids to delete.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(IEnumerable<int> departmentIdsToDelete)
        {
            db.Departments.Where(x => departmentIdsToDelete.Contains(x.DeptId)).ToList().ForEach(x => db.Departments.Remove(x));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region Dispose Database
        /// <summary>Releases unmanaged resources and optionally releases managed resources.</summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

Assignment/Assignment/Views/Assignment9/Index.cshtml
@model IPagedList<Assignment.Models.Department>
@using PagedList.Mvc;
@using PagedList;

<script src="~/Scripts/Script.js"></script>

<div class="container mx-auto w-100 py-5 my-5">
    <h2 class="text-center mb-3">Employees</h2>
    <div class="row mb-3">
        <div class="col-sm-6 col-xs-6 col-md-6">
            <div class="search-container">
                @using (@Html.BeginForm("Index", "Assignment9", FormMethod.Get, htmlAttributes: new { @class = "mt-3" }))
                {
                    <div class="form-inline">
                        <text class="font-weight-bold mr-2">Search:</text>
                        @Html.TextBox("Search", null, new { placeholder = "Search", @class = "form-control w-75 mr-2" })
                        <button type="submit" class="btn btn-search btn-info"><i class="fa fa-search"></i></button>
                    </div>
                }
            </div>
        </div>
    </div>
    @using (Html.BeginForm("Delete", "Assignment9", FormMethod.Post))
    {
        <input type="submit" value="Delete selected departments" class="btn btn-danger float-right mb-3" />
        <div class="rTable w-100 mx-auto">
            <div class="rTableRow bg-dark text-white links">
                <div class="rTableHead"><input type="checkbox" name="checkAll" id="checkAll" class="mr-3" /><strong>Select All</strong></div>
                <div class="rTableHead"><strong>@Html.ActionLink("Department Name", "Index", new { sortBy = ViewBag.DeptNameSort, search = Request["search"] })</strong></div>
                <div class="rTableHead"><strong>@Html.ActionLink("Department Location", "Index", new { sortBy = ViewBag.DeptLocationSort, search = Request["search"] })</strong></div>
                <div class="rTableHead"><strong>@Html.DisplayNameFor(model => model.First().EmployeeCount)</strong></div>
            </div>
            @foreach (var item in Model)
            {
                <div class="rTableRow">
                    <div class="rTableCell"><input type="checkbox" name="departmentIdsToDelete" id="departmentIdsToDelete" value="@item.DeptId" /></div>
                    <div class="rTableCell">@Html.DisplayFor(modelItem => item.DeptName)</div>
                    <div class="rTableCell">@Html.DisplayFor(model => item.DeptLocation)</div>
                    <div class="rTableCell">@Html.DisplayFor(modelItem => item.EmployeeCount)</div>
                </div>
            }
        </div>
    }
    <div class="btn btn-group-lg w-100">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = Request.QueryString["search"], sortBy = Request["sortBy"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, LiElementClasses = new string[] { "page-item pagecount" } })
    </div>
</div>